---

- name: Template workers file
  template:
    src: workers.j2
    dest: "{{ spark_dir }}/conf/workers"
    group: "{{ spark_group }}"
    owner: "{{ spark_user }}"
    mode: 0644
  tags:
    - configure

- name: Template Spark conf file
  template:
    src: spark-defaults.conf.j2
    dest: "{{ spark_dir }}/conf/spark-defaults.conf"
    group: "{{ spark_group }}"
    owner: "{{ spark_user }}"
    mode: 0644
  tags:
    - configure

- name: Template Spark env file
  template:
    src: spark-env.sh.j2
    dest: "{{ spark_dir }}/conf/spark-env.sh"
    group: "{{ spark_group }}"
    owner: "{{ spark_user }}"
    mode: 0755
  tags:
    - configure
